Huge improvement in detailed statistics
dambem/ClimateMonitorV2 pull request #71
Opened 2020-06-27 16:01 UTC by dambem

## Relevant issue
#63 
## Description of this PR
Detailed statistics for a while have been super unintuive and only work on single dates. This update improves that so that not only can you choose a multi range of dates easily, you can also see which dates are available (as some dates don't contain information about sensor details). 

Lots of code here

## Checklist
- [x ] Tests all pass

2020-06-28 10:44 UTC, M-Davies requested changes
A few issues I had when I checked out your branch:
- I get a few errors in the console when running `npm start` (which could be just my environment but it's worth checking).
<img width="1680" alt="Screenshot 2020-06-28 at 11 38 37" src="https://user-images.githubusercontent.com/25231953/85945185-fd28c680-b933-11ea-815e-3175bf12f061.png">

- Lines [202](https://github.com/dambem/ClimateMonitorV2/blob/master/ClimateMonitorV2/public/javascripts/new_mapping.js#L202), [371-374](https://github.com/dambem/ClimateMonitorV2/blob/master/ClimateMonitorV2/public/javascripts/new_mapping.js#L371-L374) and [382](https://github.com/dambem/ClimateMonitorV2/blob/master/ClimateMonitorV2/public/javascripts/new_mapping.js#L382) still have references to the deleted config.js file which I suspect is causing the 404 in the image

2020-06-28 10:44 UTC, M-Davies commented on ClimateMonitorV2/views/detailedstats.pug
>       script(type='text/javascript' src='/javascripts/config.js')
You still have references to config.js despite it being deleted

2020-06-28 10:44 UTC, M-Davies commented on ClimateMonitorV2/views/index.pug
>       script(type='text/javascript' src='/javascripts/config.js')
And here

2020-06-28 12:08 UTC, dambem commented
Ahh, that's due to config being accidentally deleted when it shouldn't be. Let me just put that back in

2020-07-01 20:48 UTC, dambem commented
Could i get an update on this @M-Davies

2020-07-02 08:14 UTC, M-Davies requested changes
A few conflicts to fix then it should be ok with me. Don't forget to add the new `GITHUB_API_TOKEN` into the config.js file

2020-07-02 12:43 UTC, M-Davies approved these changes
Looks good to me

2020-07-02 17:24 UTC, merged